# Generated by Django 3.2.5 on 2021-11-30 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradetype', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=2083)),
                ('name', models.CharField(default='Unknown', max_length=256)),
                ('duration', models.CharField(default='0 minutes', max_length=256)),
                ('director', models.CharField(default='Unknown', max_length=256)),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('genre', models.ManyToManyField(to='aboutus.Genre')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.grade')),
                ('language', models.ManyToManyField(to='aboutus.Language')),
                ('region', models.ManyToManyField(to='aboutus.Region')),
            ],
        ),
    ]
